// <auto-generated />
using System;
using MegaSenaHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MegaSenaHub.Infrastructure.Migrations
{
    [DbContext(typeof(MegaSenaHubDbContext))]
    partial class MegaSenaHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MegaSenaHub.Infrastructure.Data.Models.LotteryContestData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Accumulated")
                        .HasColumnType("boolean")
                        .HasColumnName("accumulated");

                    b.Property<string>("CombinationHash")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("combination_hash");

                    b.Property<int>("ContestNumber")
                        .HasColumnType("integer")
                        .HasColumnName("contest_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DrawDate")
                        .HasColumnType("date")
                        .HasColumnName("draw_date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source");

                    b.Property<decimal>("TotalPrize")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_prize");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lottery_contests");

                    b.HasIndex("CombinationHash")
                        .IsUnique()
                        .HasDatabaseName("ix_lottery_contests_combination_hash");

                    b.HasIndex("ContestNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_lottery_contests_contest_number");

                    b.HasIndex("DrawDate")
                        .HasDatabaseName("ix_lottery_contests_draw_date");

                    b.ToTable("lottery_contests", (string)null);
                });

            modelBuilder.Entity("MegaSenaHub.Infrastructure.Data.Models.LotteryContestNumberData", b =>
                {
                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("ContestId", "Number")
                        .HasName("pk_lottery_contest_numbers");

                    b.ToTable("lottery_contest_numbers", (string)null);
                });

            modelBuilder.Entity("MegaSenaHub.Infrastructure.Data.Models.PrizeRangeData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<int>("Hits")
                        .HasColumnType("integer")
                        .HasColumnName("hits");

                    b.Property<decimal>("PrizeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("prize_amount");

                    b.Property<int>("Winners")
                        .HasColumnType("integer")
                        .HasColumnName("winners");

                    b.HasKey("Id")
                        .HasName("pk_prize_ranges");

                    b.HasIndex("ContestId", "Hits")
                        .IsUnique()
                        .HasDatabaseName("ix_prize_ranges_contest_id_hits");

                    b.ToTable("prize_ranges", (string)null);
                });

            modelBuilder.Entity("MegaSenaHub.Infrastructure.Data.Models.UserBetData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_paid");

                    b.Property<DateTimeOffset?>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<int>("ContestNumber")
                        .HasColumnType("integer")
                        .HasColumnName("contest_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("PrizeWon")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("prize_won");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_bets");

                    b.HasIndex("ContestNumber")
                        .HasDatabaseName("ix_user_bets_contest_number");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_bets_user_id");

                    b.HasIndex("UserId", "ContestNumber")
                        .HasDatabaseName("ix_user_bets_user_id_contest_number");

                    b.ToTable("user_bets", (string)null);
                });

            modelBuilder.Entity("MegaSenaHub.Infrastructure.Data.Models.UserBetNumberData", b =>
                {
                    b.Property<Guid>("UserBetId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_bet_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("UserBetId", "Number")
                        .HasName("pk_user_bet_numbers");

                    b.ToTable("user_bet_numbers", (string)null);
                });

            modelBuilder.Entity("MegaSenaHub.Infrastructure.Data.Models.LotteryContestNumberData", b =>
                {
                    b.HasOne("MegaSenaHub.Infrastructure.Data.Models.LotteryContestData", "Contest")
                        .WithMany("Numbers")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lottery_contest_numbers_lottery_contests_contest_id");

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("MegaSenaHub.Infrastructure.Data.Models.PrizeRangeData", b =>
                {
                    b.HasOne("MegaSenaHub.Infrastructure.Data.Models.LotteryContestData", "Contest")
                        .WithMany("PrizeRanges")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prize_ranges_lottery_contests_contest_id");

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("MegaSenaHub.Infrastructure.Data.Models.UserBetNumberData", b =>
                {
                    b.HasOne("MegaSenaHub.Infrastructure.Data.Models.UserBetData", "UserBet")
                        .WithMany("Numbers")
                        .HasForeignKey("UserBetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_bet_numbers_user_bets_user_bet_id");

                    b.Navigation("UserBet");
                });

            modelBuilder.Entity("MegaSenaHub.Infrastructure.Data.Models.LotteryContestData", b =>
                {
                    b.Navigation("Numbers");

                    b.Navigation("PrizeRanges");
                });

            modelBuilder.Entity("MegaSenaHub.Infrastructure.Data.Models.UserBetData", b =>
                {
                    b.Navigation("Numbers");
                });
#pragma warning restore 612, 618
        }
    }
}
